### ISSUE TITLE
There are no 'refresh' function in the CMS Window for the Data in the Table

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/Condo-Management-System#16]
**Describe the bug**
The search button works. The only problem is that after searching for a particular data, it would not refresh and show all the datas. It would stay and only show the searched data. 
![Before](https://user-images.githubusercontent.com/99312804/180585824-a4f23686-af5f-4bb8-ad4f-dbe00113d7ff.JPG)
![After Searching, It would not show the other data](https://user-images.githubusercontent.com/99312804/180585827-7533b8ac-d45a-40f4-9442-f60e7287eaef.JPG)

 
**Reproduce the bug**
Search for a Data 
After the Data Search, you cannot see the previous datas in the table.

**Expected behavior**
It may be better if there are a refresh function that would reset the data after the user finished searching.

**Comment by BeepBoopBit** [comment]
If you want to see all values again, you need to make the Search Bar **blank** and press the Search Button. However, I'll implement a refresh button

**Comment by BeepBoopBit** [comment]
Resolve at #23
