### ISSUE TITLE
The Values in the table can be edited, But it would not update the Description Window

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/Condo-Management-System#19]
**Describe the bug**
In the CMS Window, the user can edit the values in the table. But after editing , it would not change or update the new values for the other windows. Like the Description and Edit Condo Unit Windows. 
![Values in the Table can be Edited, But would not update the Description Window](https://user-images.githubusercontent.com/99312804/180603472-462feff2-d5a1-43f0-890d-0636d4dc11a8.JPG)

![Edit Part2](https://user-images.githubusercontent.com/99312804/180603474-9e300abe-5781-4229-95e4-6287a705a58c.JPG)
![Ediit Part3](https://user-images.githubusercontent.com/99312804/180603484-9b63154e-bffe-48ca-9b88-fe76c0eac0cc.JPG)

**Reproduce the bug**
Try to Change the Value in the Table
See the Description Window or Edit Condo Unit Window
See that it would not update the value.

**Expected behavior**
I think that the table should not be editable. You can edit its table properties in the GUI and uncheck the editable features. If the team wants it to stay editable, it should then update other windows.

**Comment by BeepBoopBit** [comment]
You're right, values shouldn't be edited in the table. I'm reassigning this @paulreonal since this is not by job.

**Comment by BeepBoopBit** [comment]
Forgot to push it separately. It was resolve at #24
