### ISSUE TITLE
My Inputs in the Add Amenities was mixed with my inputs in the Details Table and Unclickable button

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/Condo-Management-System#27]
**Describe the bug**
My Inputs in the Add Amenities was mixed with my inputs in the Details Table. Also, I clicked the 'back button'  to go to the CMS Window and when I wanted to go back to the Description of the unit. It made the Edit Description Button Unclickable. 
![My Inputs in the Add Amenities was mixed with the Details Table](https://user-images.githubusercontent.com/99312804/182011092-c6a2b95c-438f-4154-8c6e-993d31da4498.JPG)

**To Reproduce**
1. Go to 'Edit Description and Add Amenities and Details. Save it.'
2. Click on Back Button to go straight to the CMS Window
3. Re-open the same unit and See the mixed results. Also the Edit Description would be unclickable.

**Expected behavior**
It should not mixed with the values of Amenities and Details. The Edit Description should also be clickable.

**Comment by BeepBoopBit** [comment]
resolve at #30
