### ISSUE TITLE
Values in all of the table will sometimes mixed within a single table. 

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/Condo-Management-System#28]
**Describe the bug**
Values in all of the table will sometimes mixed within a single table. Refresh function would fix the problem temporarily. But after a few searches and refreshes, it would then again mix all the values into a singular table.

![Values in all of the table will sometimes mixed within a single table](https://user-images.githubusercontent.com/99312804/182011302-e43d8255-4656-4da6-8ec4-a2c9029f3b26.JPG)

**To Reproduce**
1. Go to 'the CMS Window and Search and Refresh the tables'
2. See the Values in the Table. It would mixed. 
3. See error

**Expected behavior**
It should not mixed with the values from the other tables

**Comment by BeepBoopBit** [comment]
Resolve at #29
