### ISSUE TITLE
If you edited the Floor1, Unit201 in the program. The Edit Condo Button would not work on other units of the floor

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/Condo-Management-System#31]
**Describe the bug**
If you edited the Floor1, Unit201 in the program. The Edit Condo Button would not work on the other units. This particular problem only occurs on the Floor1 table of the window. I have tried editing the amenities and details of the other floors but this particular problem did not occur on any of them. 

Edit Condo Unit is not working on any other units on the floor1
![Edit condo unit boom](https://user-images.githubusercontent.com/99312804/182189254-f6eff46b-3ae5-46ef-a66f-0ceed0e47c72.JPG)

Edit Condo Unit only works on Unit 201
![edit condo123](https://user-images.githubusercontent.com/99312804/182189841-7a9110e7-f160-4c9e-a3f2-f3cdc61db486.JPG)

**To Reproduce**
1. Go to Edit description and edit the amenities or details
2. Click on confirm and try to edit condo unit the other units
3. See error it would not work

**Expected behavior**
it should still work not only on the unit 201 but the other units of the floor

**Comment by BeepBoopBit** [comment]
Resolve at #33
