### ISSUE TITLE
The Added Amenities would not be showing in the table. Also removing the same amenity twice makes the edit description unfunctional

### ISSUE THREAD

**Issue by braiee** [BeepBoopBit/Condo-Management-System#32]
**Describe the bug**
The Added Amenities would not be showing in the table after the user input. Also removing an amenity does not work, if you tried to remove the same amenity twice, it makes the edit description button unfunctional and not working. 
![edit and amenitions](https://user-images.githubusercontent.com/99312804/182192513-b97a32a5-1826-4174-9c14-050997e291f6.JPG)
![edit and emetnison 2](https://user-images.githubusercontent.com/99312804/182192522-96c617d2-abd7-4654-bbac-c701c60749e6.JPG)

**To Reproduce**
1. Go to edit amenities
2. remove and add amenity 
3. see that it would not be removed and would not add new amenity
4. remove the same amenity again, then after confirming open the same unit 
5. click the edit description button and it would not work

**Expected behavior**
The added amenities should be seen in the table and the remove amenity function should remove the amenity and should not cause the edit description button to not work

**Comment by BeepBoopBit** [comment]
Resolve at #33
